[project]
name = "ml-framework-fudanai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "networkx>=3.4.2",
    "pandas>=2.2.3",
    "pydot>=4.0.0",
    "scikit-learn>=1.6.1",
]
